version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: 'friday'
    target-branch: update/dependencies
    labels: ['dependencies']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: 'friday'
    target-branch: update/dependencies
    labels: ['dependencies']
