/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaygroundIndexRouteImport } from './routes/playground/index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as Playground2IndexRouteImport } from './routes/playground/2/index'
import { Route as Playground1IndexRouteImport } from './routes/playground/1/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundIndexRoute = PlaygroundIndexRouteImport.update({
  id: '/playground/',
  path: '/playground/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Playground2IndexRoute = Playground2IndexRouteImport.update({
  id: '/playground/2/',
  path: '/playground/2/',
  getParentRoute: () => rootRouteImport,
} as any)
const Playground1IndexRoute = Playground1IndexRouteImport.update({
  id: '/playground/1/',
  path: '/playground/1/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/playground/': typeof PlaygroundIndexRoute
  '/playground/1/': typeof Playground1IndexRoute
  '/playground/2/': typeof Playground2IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/playground': typeof PlaygroundIndexRoute
  '/playground/1': typeof Playground1IndexRoute
  '/playground/2': typeof Playground2IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/playground/': typeof PlaygroundIndexRoute
  '/playground/1/': typeof Playground1IndexRoute
  '/playground/2/': typeof Playground2IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog/$slug'
    | '/playground/'
    | '/playground/1/'
    | '/playground/2/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blog/$slug' | '/playground' | '/playground/1' | '/playground/2'
  id:
    | '__root__'
    | '/'
    | '/blog/$slug'
    | '/playground/'
    | '/playground/1/'
    | '/playground/2/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogSlugRoute: typeof BlogSlugRoute
  PlaygroundIndexRoute: typeof PlaygroundIndexRoute
  Playground1IndexRoute: typeof Playground1IndexRoute
  Playground2IndexRoute: typeof Playground2IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/': {
      id: '/playground/'
      path: '/playground'
      fullPath: '/playground/'
      preLoaderRoute: typeof PlaygroundIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/2/': {
      id: '/playground/2/'
      path: '/playground/2'
      fullPath: '/playground/2/'
      preLoaderRoute: typeof Playground2IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/1/': {
      id: '/playground/1/'
      path: '/playground/1'
      fullPath: '/playground/1/'
      preLoaderRoute: typeof Playground1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogSlugRoute: BlogSlugRoute,
  PlaygroundIndexRoute: PlaygroundIndexRoute,
  Playground1IndexRoute: Playground1IndexRoute,
  Playground2IndexRoute: Playground2IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
