name: CI
on:
  pull_request:
    branches: [main, 'develop']
    paths-ignore:
      - 'posts/**'
      - 'docs/**'
      - 'README.md'
jobs:
  unittests:
    name: Unit tests
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 11.1.2
          run_install: false
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Unit tests
        run: pnpm exec vp test
  # e2e:
  #   needs: unittests
  #   name: E2E tests
  #   timeout-minutes: 30
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: pnpm/action-setup@v4
  #       with:
  #         version: 11.1.2
  #         run_install: false
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 20
  #         cache: 'pnpm'
  #         cache-dependency-path: pnpm-lock.yaml
  #     - name: Install dependencies
  #       run: pnpm install --frozen-lockfile
  #     - name: Install Playwright Browsers
  #       run: pnpm exec playwright install --with-deps
  #     - name: Run Playwright tests
  #       run: pnpm exec playwright test
  #     - uses: actions/upload-artifact@v3
  #       if: always()
  #       with:
  #         name: playwright-report
  #         path: playwright-report/
  #         retention-days: 30
  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 11.1.2
          run_install: false
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: NODE_OPTIONS=--dns-result-order=ipv4first pnpm exec vp build
